"""Adding proof-of-work challenge value.

Revision ID: 92a0e93b4dea
Revises: e442fd8d7b7f
Create Date: 2017-05-17 07:01:02.247619

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '92a0e93b4dea'
down_revision = 'e442fd8d7b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pow_challenge', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pow_challenge')
    # ### end Alembic commands ###
